//@ts-nocheck
/**
 * Standalone HTML Exporter for MD → Docs.
 * Bundles the document with full CSS, KaTeX styles, and Mermaid assets into an offline-ready HTML file.
 */
import { baseStyle, pageStyle } from "./renderHtml";

export function exportStandaloneHtml(
  renderedHtml: string,
  styles: any,
  title: string = "document",
  pages: string[] = []
): string {
  const content = pages.length > 0 ? pages.map((p, idx) => `
    <div class="page-container" style="max-width:850px;margin:24px auto;background:#fff;padding:48px 56px;box-shadow:0 4px 16px rgba(0,0,0,0.08);border-radius:8px;position:relative;">
      <div style="${baseStyle(styles)}">
        ${p}
      </div>
      <div style="text-align:center;font-size:8pt;color:#94a3b8;margin-top:32px;border-top:1px solid #f1f5f9;padding-top:12px;">
        Page ${idx + 1} of ${pages.length} · Generated by MD → Docs
      </div>
    </div>
  `).join("\n") : `
    <div class="page-container" style="max-width:850px;margin:24px auto;background:#fff;padding:48px 56px;box-shadow:0 4px 16px rgba(0,0,0,0.08);border-radius:8px;">
      <div style="${baseStyle(styles)}">
        ${renderedHtml}
      </div>
    </div>
  `;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} | MD → Docs</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.8/dist/katex.min.css">
  <style>
    body {
      margin: 0;
      padding: 24px;
      background-color: #f8fafc;
      font-family: ${styles.page?.fontFamily || "system-ui, -apple-system, sans-serif"};
      color: ${styles.page?.textColor || "#1e293b"};
      line-height: 1.6;
    }
    @media print {
      body { background: transparent; padding: 0; }
      .page-container { margin: 0; box-shadow: none; border-radius: 0; page-break-after: always; }
    }
    pre { background: #f1f5f9; padding: 12px; border-radius: 6px; overflow-x: auto; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; }
    th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }
    .mermaid-diagram svg { max-width: 100%; height: auto; display: block; margin: 0 auto; }
    .gfm-callout { margin: 14px 0; padding: 12px 16px; border-left: 4px solid; border-radius: 4px; }
  </style>
</head>
<body>
  ${content}

  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script>
    mermaid.initialize({ startOnLoad: true, theme: 'neutral' });
  </script>
</body>
</html>`;
}
